// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-OZpZsx7ilJ2tH-f9uWE88eDuXoZG0uc',
    appId: '1:426789890498:web:8180f33b4878284c298e5b',
    messagingSenderId: '426789890498',
    projectId: 'assetpulse-pro',
    authDomain: 'assetpulse-pro.firebaseapp.com',
    storageBucket: 'assetpulse-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3dWyISDmd5szsr_ttYuID03a7nIEerA',
    appId: '1:426789890498:android:a5060acdb55e5cae298e5b',
    messagingSenderId: '426789890498',
    projectId: 'assetpulse-pro',
    storageBucket: 'assetpulse-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuq6tQtXVo0Y9KogUuAZI8Wm6Qj896d_8',
    appId: '1:426789890498:ios:9f4b48a2569d94ed298e5b',
    messagingSenderId: '426789890498',
    projectId: 'assetpulse-pro',
    storageBucket: 'assetpulse-pro.firebasestorage.app',
    iosBundleId: 'com.assetpulse.assetPulsePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuq6tQtXVo0Y9KogUuAZI8Wm6Qj896d_8',
    appId: '1:426789890498:ios:9f4b48a2569d94ed298e5b',
    messagingSenderId: '426789890498',
    projectId: 'assetpulse-pro',
    storageBucket: 'assetpulse-pro.firebasestorage.app',
    iosBundleId: 'com.assetpulse.assetPulsePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-OZpZsx7ilJ2tH-f9uWE88eDuXoZG0uc',
    appId: '1:426789890498:web:5dbc62addc34797d298e5b',
    messagingSenderId: '426789890498',
    projectId: 'assetpulse-pro',
    authDomain: 'assetpulse-pro.firebaseapp.com',
    storageBucket: 'assetpulse-pro.firebasestorage.app',
  );
}
