import 'dart:io';
import 'package:excel/excel.dart';

void main() {
  print('Generating comprehensive Sample Excel files for Actuators and Brakes...');

  // ==========================================
  // 1. ACTUATORS DATASET
  // ==========================================
  final actHeaders = [
    'type', 'name', 'status', 'installationDate', 'parentEquipment', 'compatibleSpares', 'spareLocation', 'isCritical',
    'actuatorType', 'torqueOrThrust', 'operatingTimeSeconds', 'controlSignal',
    'valveType', 'valveSize', 'valveFlangeStandard',
    'make', 'model', 'serialNo', 'manufacturingYear', 'poNo', 'rfidTag', 'seqNo',
  ];

  final actRows = [
    [
      'actuator',
      'BF-1 GCP Primary Sluice Valve Actuator',
      'active',
      '2023-05-10',
      'BF-1-GCP',
      'BF-1-GCP; BF-2-GCP',
      '',
      'YES',
      'Electric Multi-Turn Actuator (Rotork IQ / Auma SA)',
      '450',
      '45',
      '4-20 mA Analog (Modulating / Inching)',
      'Gate Valve',
      'DN 350 / 14"',
      'ISO 5210 (Multi-Turn)',
      'Rotork',
      'IQ35-F14',
      'ROT-2023-8841',
      '2023',
      'PO-450091',
      'E28011700000051A',
      '001',
    ],
    [
      'actuator',
      'Cooling Water Header Butterfly Valve Actuator',
      'active',
      '2022-11-15',
      'CW-PUMP-01',
      'CW-PUMP-01; CW-PUMP-02',
      '',
      'YES',
      'Electric Part-Turn / Quarter-Turn (Rotork IQT / Auma SG)',
      '600',
      '15',
      'ON-OFF (24V DC / 110V AC Command)',
      'Butterfly Valve',
      'DN 300 / 12"',
      'ISO 5211 - F10 / F12',
      'Auma',
      'SG 07.2-F10',
      'AUM-44129',
      '2022',
      'PO-450077',
      '',
      '002',
    ],
    [
      'actuator',
      'BF-2 Hot Blast Stove Combustion Air Damper Actuator',
      'active',
      '2023-08-20',
      'BF-2-STOVE',
      'BF-1-STOVE; BF-2-STOVE',
      '',
      'YES',
      'Electric Part-Turn / Quarter-Turn (Rotork IQT / Auma SG)',
      '1000',
      '25',
      'Profibus DP',
      'Louver / Guillotine Damper',
      '1200 x 1200 mm',
      'ISO 5211 - F14 / F16',
      'Rotork',
      'IQT-1000-Profibus',
      'ROT-99214',
      '2023',
      'PO-450122',
      'E28011700000052B',
      '003',
    ],
    [
      'actuator',
      'Coke Oven Gas Main Emergency Shut-off Valve (ESD)',
      'active',
      '2023-03-12',
      'COG-HEADER-01',
      'COG-HEADER-01',
      '',
      'YES',
      'Pneumatic Single-Acting (Spring Return)',
      '350',
      '2',
      'ON-OFF (24V DC / 110V AC Command)',
      'Ball Valve',
      'DN 150 / 6"',
      'ISO 5211 - F10 / F12',
      'Festo',
      'DFPD-300-RP-90-RS60-F1012',
      'FES-77124',
      '2023',
      'PO-450201',
      '',
      '004',
    ],
    [
      'actuator',
      'Slag Granulation Water Flow Control Valve Actuator',
      'active',
      '2022-09-05',
      'SLAG-PUMP-01',
      'SLAG-PUMP-01; SLAG-PUMP-02',
      '',
      'NO',
      'Pneumatic Double-Acting',
      '1200',
      '8',
      '4-20 mA Analog (Modulating / Inching)',
      'Butterfly Valve',
      'DN 400 / 16"',
      'ISO 5211 - F14 / F16',
      'Rotex',
      'EC-120-DA',
      'ROX-33190',
      '2022',
      'PO-450188',
      '',
      '005',
    ],
    [
      'actuator',
      'Blast Furnace Snort Valve High-Speed Hydraulic Actuator',
      'active',
      '2023-07-14',
      'BF-1-BLOWER',
      'BF-1-BLOWER; BF-2-BLOWER',
      '',
      'YES',
      'Electro-Hydraulic Actuator',
      '25',
      '1.5',
      '4-20 mA Analog (Modulating / Inching)',
      'Control Valve',
      'DN 500 / 20"',
      'Custom Flange',
      'Rexroth Bosch',
      'SHA-250-Linear',
      'REX-11029',
      '2023',
      'PO-450300',
      'E28011700000053C',
      '006',
    ],
    [
      'actuator',
      'Ladle Turret Emergency Shut-Off Gate Hydraulic Cylinder',
      'active',
      '2022-01-20',
      'LADLE-TURRET-01',
      'LADLE-TURRET-01',
      '',
      'YES',
      'Hydraulic Cylinder Actuator',
      '80',
      '5',
      'ON-OFF (24V DC / 110V AC Command)',
      'Hopper Sector Gate',
      '800 x 800 mm',
      'Custom Flange',
      'Hydac',
      'HC-160/100-500',
      'HYD-88210',
      '2021',
      'PO-450119',
      '',
      '007',
    ],
    [
      'actuator',
      'Rotork IQ25 Multi-Turn Actuator 250Nm Spare',
      'spare',
      '',
      '',
      'BF-1-GCP; BF-2-GCP; WTP-PUMP-01',
      'Automation Warehouse - Rack A3',
      'YES',
      'Electric Multi-Turn Actuator (Rotork IQ / Auma SA)',
      '250',
      '30',
      '4-20 mA Analog (Modulating / Inching)',
      'Gate Valve',
      'DN 200 / 8"',
      'ISO 5210 (Multi-Turn)',
      'Rotork',
      'IQ25-F10',
      'ROT-SP-4410',
      '2023',
      'PO-450411',
      '',
      '008',
    ],
    [
      'actuator',
      'Auma SG 05.1 Part-Turn Actuator 300Nm Spare',
      'spare',
      '',
      '',
      'CW-PUMP-01; CW-PUMP-02',
      'Electrical Store - Bay 2',
      'NO',
      'Electric Part-Turn / Quarter-Turn (Rotork IQT / Auma SG)',
      '300',
      '15',
      '4-20 mA Analog (Modulating / Inching)',
      'Butterfly Valve',
      'DN 200 / 8"',
      'ISO 5211 - F05 / F07',
      'Auma',
      'SG 05.1-F07',
      'AUM-SP-9912',
      '2023',
      'PO-450422',
      '',
      '009',
    ],
  ];

  // ==========================================
  // 2. BRAKES DATASET
  // ==========================================
  final brakeHeaders = [
    'type', 'name', 'status', 'installationDate', 'parentEquipment', 'compatibleSpares', 'spareLocation', 'isCritical',
    'brakeType', 'voltageType', 'voltageRating', 'thrusterCapacityKg', 'brakingTorqueNm',
    'drumDiaMm', 'drumWidthMm', 'drumInstallation', 'mountingBoltSize', 'noOfMountingBolts', 'mountingLengthMm', 'mountingWidthMm',
    'brakeShoeLining', 'make', 'model', 'serialNo', 'manufacturingYear', 'poNo', 'rfidTag', 'seqNo',
  ];

  final brakeRows = [
    [
      'brake',
      'BF-1 Cast House Crane 75T Main Hoist EHT Thruster Brake',
      'active',
      '2022-08-10',
      'BF1-CH-CRANE',
      'BF1-CH-CRANE; BF2-CH-CRANE',
      '',
      'YES',
      'AC Electro-Hydraulic Thruster (EHT) Brake',
      'AC',
      '415',
      '125',
      '1850',
      '400',
      '190',
      '1-M 1-GB (Dual Drive)',
      'M20',
      '6',
      '855',
      '165',
      'Non-Asbestos Heavy Duty Woven Friction Liner',
      'Sterling',
      'MDT-400/125 (Ed 121/6)',
      'STR-99104',
      '2022',
      'PO-450066',
      'E28011700000061A',
      '001',
    ],
    [
      'brake',
      'Baghouse Crane Long Travel (LT) EHT Thruster Brake',
      'active',
      '2023-04-12',
      'BH-CRANE-01',
      'BH-CRANE-01; BF1-SGC-01',
      '',
      'YES',
      'AC Electro-Hydraulic Thruster (EHT) Brake',
      'AC',
      '415',
      '30',
      '450',
      '250',
      '130',
      'Gearbox Input Shaft (GB)',
      'M12',
      '4',
      '490',
      '120',
      'Semi-Metallic High-Friction Shoe Lining',
      'Electro Power',
      'EP-250/30 (Ed 30/5)',
      'EP-44192',
      '2023',
      'PO-450144',
      '',
      '002',
    ],
    [
      'brake',
      'BF-2 Ladle Crane Cross Travel (CT) Thruster Brake',
      'active',
      '2023-06-18',
      'BF2-LADLE-CRANE',
      'BF1-LADLE-CRANE; BF2-LADLE-CRANE',
      '',
      'NO',
      'AC Electro-Hydraulic Thruster (EHT) Brake',
      'AC',
      '415',
      '23',
      '220',
      '160',
      '80',
      'Motor Shaft (M)',
      'M10',
      '4',
      '410',
      '68',
      'Non-Asbestos Organic Lining',
      'Sterling',
      'MDT-160/23 (Ed 23/5)',
      'STR-33219',
      '2023',
      'PO-450190',
      '',
      '003',
    ],
    [
      'brake',
      'BF-1 HMC 15T Aux Hoist DC Electromagnetic Brake',
      'active',
      '2022-10-04',
      'BF1-HMC-01',
      'BF1-HMC-01; BF2-HMC-01',
      '',
      'YES',
      'DC Solenoid Drum Brake',
      'DC',
      '110',
      '',
      '320',
      '200',
      '100',
      'Gearbox Input Shaft (GB)',
      'M12',
      '4',
      '350',
      '65',
      'Molded Asbestos-Free Lining',
      'BCH Electric',
      'BCH-200-DC110',
      'BCH-88210',
      '2022',
      'PO-450099',
      'E28011700000062B',
      '004',
    ],
    [
      'brake',
      'Raw Material Reclaimer Winch Motor Rear Fail-Safe DC Brake',
      'active',
      '2023-02-14',
      'RMHS-RECLAIMER-01',
      'RMHS-RECLAIMER-01; RMHS-STACKER-01',
      '',
      'YES',
      'Fail-Safe Spring Applied DC Brake',
      'DC',
      '190',
      '',
      '150',
      '220',
      '20',
      'Direct Coupling Mounted',
      'M10',
      '4',
      '280',
      '280',
      'Friction Pad Disc Lining',
      'Intorq / Kendrion',
      'BFK458-16E',
      'INT-77102',
      '2023',
      'PO-450255',
      '',
      '005',
    ],
    [
      'brake',
      'Main Sinter Plant Downhill Overland Conveyor Emergency Hydraulic Disc Brake',
      'active',
      '2021-09-30',
      'SP-CONVEYOR-01',
      'SP-CONVEYOR-01',
      '',
      'YES',
      'Hydraulic Caliper Disc Brake',
      '',
      '',
      '',
      '12500',
      '800',
      '30',
      'Gearbox Input Shaft (GB)',
      'M24',
      '8',
      '620',
      '450',
      'High Thermal Dissipation Sintered Metallic Pads',
      'Svendborg Brakes',
      'BSFI 300-MS',
      'SVN-12093',
      '2021',
      'PO-450020',
      'E28011700000063C',
      '006',
    ],
    [
      'brake',
      'Primary Boiler FD Fan Emergency Pneumatic Disc Brake',
      'active',
      '2022-12-08',
      'BOILER-FD-01',
      'BOILER-FD-01; BOILER-ID-01',
      '',
      'NO',
      'Pneumatic Disc Brake',
      '',
      '',
      '',
      '1400',
      '450',
      '25',
      'Motor Shaft (M)',
      'M16',
      '4',
      '380',
      '380',
      'Organic Resin Bonded Friction Pads',
      'Twiflex',
      'T20 Pneumatic Caliper',
      'TWF-66104',
      '2022',
      'PO-450177',
      '',
      '007',
    ],
    [
      'brake',
      'MDT-250 Drum Thruster Brake Assembly 34kg Spare',
      'spare',
      '',
      '',
      'BF1-HMC-01; BF2-HMC-01; BH-CRANE-01',
      'Crane Workshop - Bay 3',
      'YES',
      'AC Electro-Hydraulic Thruster (EHT) Brake',
      'AC',
      '415',
      '34',
      '550',
      '250',
      '130',
      'Gearbox Input Shaft (GB)',
      'M12',
      '4',
      '490',
      '120',
      'Non-Asbestos Molded Friction Liner',
      'Sterling',
      'MDT-250/34',
      'STR-SP-882',
      '2023',
      'PO-450390',
      '',
      '008',
    ],
    [
      'brake',
      'BCH 200mm DC 110V Electromagnetic Brake Assembly Spare',
      'spare',
      '',
      '',
      'BF1-HMC-01; BF2-HMC-01',
      'Electrical Substation Store - Shelf B1',
      'YES',
      'DC Solenoid Drum Brake',
      'DC',
      '110',
      '',
      '320',
      '200',
      '100',
      'Gearbox Input Shaft (GB)',
      'M12',
      '4',
      '350',
      '65',
      'Semi-Metallic Molded Lining',
      'BCH Electric',
      'BCH-200-DC110',
      'BCH-SP-104',
      '2023',
      'PO-450410',
      '',
      '009',
    ],
  ];

  // =========================================================================
  // FILE 1: Sample_Actuators_Import.xlsx (Standalone Actuators Sheet)
  // =========================================================================
  final excelAct = Excel.createExcel();
  final defaultSheetAct = excelAct.getDefaultSheet() ?? 'Sheet1';
  excelAct.rename(defaultSheetAct, 'Actuator_Template');
  final sheetAct = excelAct['Actuator_Template'];
  sheetAct.appendRow(actHeaders.map((h) => TextCellValue(h)).toList());
  for (var row in actRows) {
    sheetAct.appendRow(row.map((val) => TextCellValue(val)).toList());
  }
  final bytesAct = excelAct.save();
  if (bytesAct != null) {
    File('Sample_Actuators_Import.xlsx').writeAsBytesSync(bytesAct);
    print('Generated Sample_Actuators_Import.xlsx (${actRows.length} Actuators)');
  }

  // =========================================================================
  // FILE 2: Sample_Brakes_Import.xlsx (Standalone Brakes Sheet)
  // =========================================================================
  final excelBrk = Excel.createExcel();
  final defaultSheetBrk = excelBrk.getDefaultSheet() ?? 'Sheet1';
  excelBrk.rename(defaultSheetBrk, 'Brake_Template');
  final sheetBrk = excelBrk['Brake_Template'];
  sheetBrk.appendRow(brakeHeaders.map((h) => TextCellValue(h)).toList());
  for (var row in brakeRows) {
    sheetBrk.appendRow(row.map((val) => TextCellValue(val)).toList());
  }
  final bytesBrk = excelBrk.save();
  if (bytesBrk != null) {
    File('Sample_Brakes_Import.xlsx').writeAsBytesSync(bytesBrk);
    print('Generated Sample_Brakes_Import.xlsx (${brakeRows.length} Brakes)');
  }

  // =========================================================================
  // FILE 3: Sample_Actuators_and_Brakes_Import.xlsx (Combined Multi-Sheet)
  // =========================================================================
  final excelCombined = Excel.createExcel();
  final defaultSheetComb = excelCombined.getDefaultSheet() ?? 'Sheet1';
  excelCombined.rename(defaultSheetComb, 'Actuators');
  
  final sheetCombAct = excelCombined['Actuators'];
  sheetCombAct.appendRow(actHeaders.map((h) => TextCellValue(h)).toList());
  for (var row in actRows) {
    sheetCombAct.appendRow(row.map((val) => TextCellValue(val)).toList());
  }

  final sheetCombBrk = excelCombined['Brakes'];
  sheetCombBrk.appendRow(brakeHeaders.map((h) => TextCellValue(h)).toList());
  for (var row in brakeRows) {
    sheetCombBrk.appendRow(row.map((val) => TextCellValue(val)).toList());
  }

  // Reference Sheet
  final sheetRef = excelCombined['Reference_Guide'];
  sheetRef.appendRow([TextCellValue('TECHNICAL REFERENCE GUIDE FOR ACTUATORS & BRAKES')]);
  sheetRef.appendRow([TextCellValue('Field'), TextCellValue('Valid Standard Options / Format'), TextCellValue('Engineering Notes')]);
  sheetRef.appendRow([TextCellValue('actuatorType'), TextCellValue('Electric Multi-Turn | Electric Part-Turn | Pneumatic Single-Acting | Pneumatic Double-Acting | Electro-Hydraulic | Hydraulic Cylinder'), TextCellValue('Auto-matches form fields')]);
  sheetRef.appendRow([TextCellValue('controlSignal'), TextCellValue('4-20 mA Analog | ON-OFF (24VDC/110VAC) | Profibus DP | Modbus RTU | HART'), TextCellValue('Automation communication protocol')]);
  sheetRef.appendRow([TextCellValue('valveType'), TextCellValue('Butterfly Valve | Gate Valve | Ball Valve | Globe Valve | Louver Damper | Hopper Sector Gate'), TextCellValue('Installed valve/damper')]);
  sheetRef.appendRow([TextCellValue('valveFlangeStandard'), TextCellValue('ISO 5211 (F05/F07/F10/F12/F14/F16/F25/F30) | ISO 5210 (Multi-Turn) | Custom Flange'), TextCellValue('Mounting standard')]);
  sheetRef.appendRow([TextCellValue('brakeType'), TextCellValue('AC Electro-Hydraulic Thruster (EHT) Brake | DC Solenoid Drum Brake | Fail-Safe Spring Applied DC Brake | Hydraulic Caliper | Pneumatic Disc'), TextCellValue('Braking technology')]);
  sheetRef.appendRow([TextCellValue('voltageType'), TextCellValue('AC | DC'), TextCellValue('Power supply voltage')]);
  sheetRef.appendRow([TextCellValue('drumInstallation'), TextCellValue('1-M 1-GB (Dual Drive) | Motor Shaft (M) | Gearbox Input Shaft (GB) | Direct Coupling Mounted'), TextCellValue('Installation position')]);

  final bytesComb = excelCombined.save();
  if (bytesComb != null) {
    File('Sample_Actuators_and_Brakes_Import.xlsx').writeAsBytesSync(bytesComb);
    print('Generated Sample_Actuators_and_Brakes_Import.xlsx (Combined with Reference Guide)');
  }
}
